### PR TITLE
Updating .gitignore

### PR DESCRIPTION
**Pull request by cmclane99**
Added .shh folder to ignore ssh keys. Changes made to file were reviewed successfully.

### CODE REVIEW

**Comment by fmartin7** [comment]
Created .gitignore to ignore unused and unnecessary files

**Comment by braydenflaig** [comment]
Everything seems good and organized to add to if need be later on. Made sure that the .ssh folder was added to prevent our access key weren't accidentally made public.

**Comment by StephenOK** [comment]
Well made ignore file. Covers all programs we intend to use for the app and has a robust list for the individual apps.

**Comment by TLjanelle** [comment]
Everything in the .gitignore looks good. Covers all documentation for OS and programs/ide's we will be using.

**Pull request merged**
