### PR TITLE
Fentry update install file

### PR DESCRIPTION
**Pull request by StephenOK**
Details for installing Android, SQLite3, and Django REST Framework provided.

### CODE REVIEW

**Comment by StephenOK** [comment]
Stephen O'Keefe:  Directions seem sufficiently thorough and easy to use.

**Comment by braydenflaig** [comment]
Everything that is needed for the project so far and should be easy to add to if needed later down the line.

**Comment by TLjanelle** [comment]
This is a very well thought out .gitignore file and very organized. It should be good for the start of the project.

**Comment by fmartin7** [comment]
Installation instruction are easy to perform

**Comment by cmclane99** [comment]
Instructions for setting up the project are concise and easy to follow

**Pull request merged**
