### PR TITLE
Reorganizing Files

### PR DESCRIPTION
**Pull request by StephenOK**

### CODE REVIEW

**Comment by StephenOK** [comment]
Project Structure

We decided we would include files with their own extensions in their own folders. We are following the standard structure described on: https://www.geeksforgeeks.org/android-android-apps-file-structure/

Android Studios automatically creates a structure we will implement upon. 
The app/ and gradle/ folder structure is auto generated by Android Studios.

The folder structure:
app/
java/
manifests/
res/
django/
docs/
gradle/
.gitignore

**Comment by fmartin7** [comment]
The purpose of this structure is to have an app folder and Gradle folder for the front end. We also have a Django folder for the backend. Also a docs folder for .gitignore, install files, etc.

**Comment by TLjanelle** [comment]
The file structure may need to be updated as we continue with the project, but for simplicity we will add the directories as the files are

image

**Comment by cmclane99** [comment]
The folder structure is organized and meets the requirements for our project. Changes might be needed as we continue to work on the project.

**Comment by braydenflaig** [comment]
All files that will be needed for the project seem to have a place in this project layout, if things need to be added or even take away that seems like it will be easy the way we have It.

**Pull request merged**
